using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class GodActiveUI : MonoBehaviour {

    public Text godLeftTxt;
    public GameObject godBtn;
    
    public void Active()
    {
        if (GameManager.Instance.Player.GodMode)
            return;

        GlobalValue.storeGod--;
        GameManager.Instance.Player.InitGodmode();
    }
	
	// Update is called once per frame
	void Update () {
        godBtn.SetActive(GlobalValue.storeGod > 0);
        godLeftTxt.text = GlobalValue.storeGod + "";

        if (Input.GetKeyDown(DefaultValue.Instance == null ? DefaultValueKeyboard.Instance.keyGod : DefaultValue.Instance.keyGod))
            Active();
    }
}
